---
- name: "Playbook to deprovision Amun"

  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    AMUN_INFRA_NAMESPACE: "{{ infra_namespace }}"
    AMUN_API_NAMESPACE: "{{ api_namespace }}"
    AMUN_INSPECTION_NAMESPACE: "{{ inspection_namespace }}"
      
  tasks:
    - fail: msg="Bailing out. this play requires 'AMUN_API_NAMESPACE'"
      when: AMUN_API_NAMESPACE is not defined

    - fail: msg="Bailing out. this play requires 'AMUN_INSPECTION_NAMESPACE'"
      when: AMUN_INSPECTION_NAMESPACE is not defined

    - fail: msg="Bailing out. this play requires 'AMUN_INFRA_NAMESPACE'"
      when: AMUN_INFRA_NAMESPACE is not defined

    - name: "Deprovision Amun API"
      command: oc --namespace "{{ item }}" \
        delete buildconfig,configmap,deploymentconfig,imagestream,route,secret,service \
        --selector=app=amun
      with_items:
        - "{{ AMUN_API_NAMESPACE }}"
        - "{{ AMUN_INSPECTION_NAMESPACE }}"
        - "{{ AMUN_INFRA_NAMESPACE }}"
      ignore_errors: true

    - name: "Deprovision other Amun API requirements"
      command: "oc --namespace {{ item }} \
        delete role,rolebinding,serviceaccount,template \
        --selector 'app=amun'"
      with_items:
        - "{{ AMUN_API_NAMESPACE }}"
        - "{{ AMUN_INSPECTION_NAMESPACE }}"
        - "{{ AMUN_INFRA_NAMESPACE }}"
      ignore_errors: true
